version: "3"

tasks:
  install:
    desc: Install all dependencies for the project
    cmds:
      - poetry install

  ci:
    desc: Run Github Actions CI pipeline locally
    cmds:
      - act -n

  add:
    desc: Add a new package to the project
    cmds:
      - poetry add {{.PACKAGE}}
    requires:
      vars: [PACKAGE]

  add_dev:
    desc: Add a new package to the project as a development dependency
    cmds:
      - poetry add {{.PACKAGE}} --group dev
    requires:
      vars: [PACKAGE]

  test:
    desc: Run all tests with verbose output or a specific test file
    vars:
      FILE: "{{.FILE}}"
    cmds:
      - poetry run pytest {{if .FILE}}tests/test_{{.FILE}}.py{{else}}-v{{end}}

  format:
    desc: Run code formatting and remove unused imports using Ruff
    cmds:
      - poetry run ruff check --select I,F401 --fix
      - poetry run ruff format

  lint:
    desc: Run linting using Pyrefly
    cmds:
      - poetry run pyrefly check
