version: "3"

tasks:
  test_all:
    desc: Run all tests with verbose output
    cmds:
      - poetry run pytest -v

  format_all:
    desc: Format all Python files using black
    cmds:
      - poetry run black .

  test:
    desc: Run a specific test file
    cmds:
      - poetry run pytest tests/{{.NAME}}.py
    requires:
      vars: [NAME]
