version: "3"

tasks:
  install:
    desc: Install all dependencies for the project
    cmds:
      - poetry install

  add:
    desc: Add a new package to the project
    cmds:
      - poetry add {{.PACKAGE}}
    requires:
      vars: [PACKAGE]

  add_dev:
    desc: Add a new package to the project as a development dependency
    cmds:
      - poetry add {{.PACKAGE}} --groupdev
    requires:
      vars: [PACKAGE]

  test_all:
    desc: Run all tests with verbose output
    cmds:
      - poetry run pytest -v

  format_all:
    desc: Format all Python files using black
    cmds:
      - poetry run black .

  lint:
    desc: Run pyrefly lint
    cmds:
      - poetry run pyrefly lint

  test:
    desc: Run a specific test file
    cmds:
      - poetry run pytest tests/{{.NAME}}.py
    requires:
      vars: [NAME]
