name: Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Poetry
        run: |
          pip install --upgrade pip
          pip install poetry==1.8.3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "poetry"

      - name: Install dependencies
        run: poetry install

      - name: Run pyrefly lint
        run: poetry run pyrefly check

      - name: Format code with Black
        run: poetry run black .

      - name: Run tests
        run: poetry run pytest -v
