name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Poetry
        run: |
          pip install --upgrade pip
          pip install poetry==1.8.3
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "poetry"

      - name: Install Dependencies
        run: poetry install

      - name: Lint
        run: poetry run pyrefly check

      - name: Format
        run: poetry run black .

      - name: Test
        run: poetry run pytest -v
